### PR TITLE
first cut of my changes

### PR DESCRIPTION
**Pull request by jedi4ever**
1) Did some cleanup of tabs/returns - hope that is ok
2) Changed Rakefile to use Dir.glob over Filelist (it avoid requiring rake)
3) Changed the assignment of integer to the packet to make it work under 1.9.

### CODE REVIEW

**Comment by jedi4ever** [comment]
hey, any chance of getting these in master?

**Comment by aquasync** [comment]
Hi. Sorry for the delay - just had a new baby and free time has been hard to come by! I'd prefer to leave things tab indented - could you modify the commits? Happy to merge the changes otherwise - all looks good.

**Comment by jedi4ever** [comment]
Ok, I've converted them back. Hope this is what you mean? 

Thanks for support and  congratulations on the new baby!

**Comment by jedi4ever** [comment]
ping :)

**Comment by aquasync** [comment]
Ok I've just merged this. Note that I cherry picked it as I wanted to skip type_string for now (as per earlier comment on that commit - unsure about holding shift but then sending shifted characters, and also missing final unshift), and also to amend to avoid round trip to spaces and back. I've also removed all those pesky carriage returns - remnants of the projects initial windows dev. Unless there's anything else you want to add I'll release this as 1.1.0 to fix 1.9 problems.

**Pull request closed without merging**
